services:
  - type: web
    name: notion-notes-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NOTION_CLIENT_ID
        sync: false
      - key: NOTION_CLIENT_SECRET
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: FRONTEND_URL
        value: https://notion-notes.onrender.com
    healthCheckPath: /health
    autoDeploy: true

  - type: static
    name: notion-notes-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://notion-notes-backend.onrender.com
      - key: VITE_NOTION_CLIENT_ID
        sync: false
      - key: VITE_NOTION_REDIRECT_URI
        value: https://notion-notes.onrender.com
    autoDeploy: true 